### ISSUE TITLE
Переделать gulpfile

### ISSUE THREAD

**Issue by speker2010** [moskvichev/TODO__app#17]
Переделай задачи
Сделай задачу на сборку стилей
Сделай задачу на watch + browser-sync
Я хотел запустить сборку стилей без watch и browserSync, но не смог, ты слишком намудрил с функциями

**Comment by moskvichev** [comment]
gulp - запускает все процессы одновременно
gulp build; - процесс сборки стилей
gulp watchSass; - наблюдает
gulp sync; - открывает браузер
