### ISSUE TITLE
Получение элементов по порядку

### ISSUE THREAD

**Issue by speker2010** [moskvichev/TODO__app#5]
Не ссылайся на элементы используя порядковый номер.
Так получается хрупкий код, который легко сломать и сложно модифицировать.
Например поменяешь кнопки местами и уже будет не правильно работать.
https://github.com/moskvichev/TODO__app/blob/39252605ef0c585bed444d33211e0c996c47090d/js/javascript.js#L143

В качестве решения можно сделать так:
Кнопкам даешь id или уникальные классы и ищешь по ним

**Comment by moskvichev** [comment]
Переделал
