### ISSUE TITLE
Смешаны var и let

### ISSUE THREAD

**Issue by speker2010** [moskvichev/TODO__app#7]
Определись что ты считаешь правильным и переделай

**Comment by fax1ty** [comment]
У `var` и `let` разные области видимости, возможно, кодер просто хотел ограничить видимость переменных

**Comment by speker2010** [comment]
Согласен, в отдельных случаях можно отойти от единого стиля, из-за их особенностей, но в данном случае разные объявления ничем не оправданы.
В этой репе можно было бы заменить `var` на `let` и ничего бы не изменилось.

**Comment by fax1ty** [comment]
> Согласен, в отдельных случаях можно отойти от единого стиля, из-за их особенностей, но в данном случае разные объявления ничем не оправданы.
> В этой репе можно было бы заменить `var` на `let` и ничего бы не изменилось.

Да, полностью согласен. Там всё внутри функции вызывается. Это я так, навскидку написал

**Comment by moskvichev** [comment]
объявлял переменную глобально, т.к. в последующей функции использовал, затем все переписал, а переменная осталась ->поправил.
